version: '3.7'

networks:
  caddy:

services:
  caddy:
    image: caddy:2.7.4
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
    network_mode: 'host'
    environment:
      - DB_SERVER=${DB_SERVER}