version: '3.7'

networks:
  caddy:

services:
  caddy:
    image: caddy:2.7.5
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
    networks: [ cluster ]
    ports: 
      - "${PORT:-80}:80"